### ISSUE TITLE
First Review

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/epics-containers.github.io#31]
Results of a full review of the linux tutorials from @AlexanderWells-diamond 

Here's a list of various points I've come across while going through the tutorials here: https://epics-containers.github.io/main/user/tutorials/intro.html

- [x] "Setup a Devcontainer":

The note to ensure you have installed the DevContainer extension is a little confusing. It was not obvious to me that I had just installed it as part of the RemoteDevelopment "extension", which is really a collection of 4 extensions in one. Perhaps either call out the 4 extensions that the pack will install, or tell users to ensure they have all extensions from the previous page?

- [x] "epics_devcontainer":

The "REPLACE all environment below with your details " section is a bit odd - the default checkout of the repo provided earlier in the tutorials already has good values written in it, including KUBECONFIG pointing to config_pollux and the Helm Registry pointing to helm-test.diamond.ac.uk/iocs.
As discussed, it really wasn't clear to me that I had to change the K8S_HELM_REGISTRY variable, especially as the other two variables appear to be correct

- [x] "create_beamline":

Minor typo: "To do this got to..." should be "To do this go to..."
When doing 'git commit -m "rename blxxi to bl01t"' from inside the dev container, git automatically set the author to "root" with an email of "root@pc0103.cs.diamond.ac.uk". This doesn't feel correct, and the docs should at least provide some sort of warning or guidance.
When I pushed the newly created tag, I used "git push --tags". This had the inadvertant effect of pushing your tags "23.4.1" and "23.3.1" as well. Any way to avoid this?

- [x] "deploy_example":

Probably worth putting a note somewhere to change the IOC name to the custom one, if the user in previous sections had used a custom name. 
When examining the logs of the IOC I saw this error: "recGblRecordError: devStringinEnvVar (init_record) Illegal INP parm field Illegal field value PV: BL01T-EA-IOC-01:TIMEZONE"
I'm not sure if its important, but somehow two different pods had the same IP address:
[E7](main)[bl01t]$ ec ps -w
POD                                VERSION            STATE     RESTARTS   STARTED                IP              GENERIC_IOC_IMAGE
bl01t-ea-ioc-02-6b7bcfdc78-g5bfj   2023.4.20-b12.40   Running   0          2023-04-20T12:43:50Z   172.23.168.23   ghcr.io/epics-containers/ioc-template-rtems-runtime:23.4.2
blxxi-ea-ioc-01-cf5f6d94b-sqs4c    23.3.3             Running   1          2023-04-13T10:41:36Z   172.23.168.24   ghcr.io/epics-containers/ioc-adsimdetector-linux-runtime:23.3.4
eyh46967-ioc-01-5b9944dc49-fr86k   23.4.21            Running   0          2023-04-21T09:08:12Z   172.23.168.23   ghcr.io/epics-containers/ioc-adsimdetector-linux-runtime:23.3.4

After running "c2dv --pv BL01T-EA-TST-01:IMAGE" and seeing the GUI pop up, clicking on the empty area crashes the GUI with this error:
[E7](main)[bl01t]$ c2dv --pv BL01T-EA-TST-01:IMAGE
172.23.168.23
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/c2dataviewer/view/image_display.py", line 222, in mousePressEvent
    img_width, img_height = self.calc_img_size_on_screen()
TypeError: cannot unpack non-iterable NoneType object
Fatal Python error: Aborted

Current thread 0x00007f32a27d1740 (most recent call first):
  File "/venv/lib/python3.9/site-packages/c2dataviewer/imagev.py", line 113 in imagev
  File "/venv/lib/python3.9/site-packages/c2dataviewer/c2dv.py", line 209 in main
  File "/venv/bin/c2dv", line 8 in <module>
Fatal Python error: Segmentation fault

Current thread 0x00007f32a27d1740 (most recent call first):
  File "/venv/lib/python3.9/site-packages/c2dataviewer/imagev.py", line 113 in imagev
  File "/venv/lib/python3.9/site-packages/c2dataviewer/c2dv.py", line 209 in main

  File "/venv/bin/c2dv", line 8 in <module>

I cannot run the EDM GUI from within the devcontainer, using either podman or docker. 
If I try and run the EDM GUI outside of the container, by either "./blxxi-ea-ioc-01-gui.sh" or "opi/./blxxi-ea-ioc-01-gui.sh" (from the relevant paths) I see an error:
[eyh46967@pc0103 opi]$ ./blxxi-ea-ioc-01-gui.sh
./launcher.sh: line 12: --privilege : command not found
+++ podman run --rm -d -e DISPLAY -e EPICS_CA_ADDR_LIST -e EPICS_CA_AUTO_ADDR_LIST -e EPICS_CA_SERVER_PORT -e EDMDATAFILES=/screens -v /scratch/eyh46967/dev/tmp/work-ec/bl01t/opi/bl01t-ea-ioc-01:/screens -v /tmp:/tmp -ti --net=host ghcr.io/epics-containers/edm:latest edm -x -noedit PCO.edl
f27c81cf6026c17456a299bb0cb25b335e74c23296d96e1c3f9a9b1cdf5aff72
If you run the IOC start command twice in rapid succession, it seems to start the same IOC twice and results in this error in the logs:
cas WARNING: Configured TCP port was unavailable.

cas WARNING: Using dynamically assigned TCP port 38285,
cas WARNING: but now two or more servers share the same UDP port.
cas WARNING: Depending on your IP kernel this server may not be

cas WARNING: reachable with UDP unicast (a host's IP in EPICS_CA_ADDR_LIST)
I'm additionally worried that if multiple people are running test IOCs, you may end up getting PVs from someone else's IOC? I'm not convinced I haven't falled into this as I've been working alongside some other deployed IOCs, which seem to share the same IP address

- [x] "ioc_changes":

Trying to run this command: "ec dev ioc-launch iocs/bl01t-ea-ioc-01 --tag 23.3.4" gives this error:
RuntimeError: Missing file /home/eyh46967/.bashrc_dev, please copy from .devcontainer or create your own
After our discussion we agreed this was a bug and shoul not be required

The tag number in the above command should probably be made more clear that it is NOT the same as the tag number we created in a previous step
In "Deploying a Beta IOC Instance to The Cluster" section there appears to be a malformed link to "05_deploy_example"

- [ ] "generic_ioc":

In "Prepare the New Repo for Development" it is confusing to require editing the workflow to remove "RTEMS", and then in the next bullet point explaining that tests need to be fixed (but not really, as that's done in two tutorials time). It's just a bit misleading to have the two bullet points formatted the same, when only one actually needs work.
When creating the new repo and pushing it, the CI triggers immediately. It fails again with the issue that I have UPPERCASE letters in my GH username.
In "Add ibek-defs Patch file for ADURL" the text talks about creating a folder and file, however these already appear to exist? (Note: I messed up the submodules here and so may have managed to somehow get myself into a weird state...)

Under "build the generic IOC" heading, it'd be nice to have the "ioc-adurl" string put into code formatting.
I've again hit the upper case username issue when trying to run "ec dev build"
Probably worth noting that the dev build can easily take 5+ minutes to execute.

- [ ] "debug_generic_ioc":

Under "An Easier Fix Using ADSupport" It's not terribly clear where to add the lines to the adsupport.sh file - they have to go into the configure/CONFIG_SITE.linux86_64.Common section
When updating the "Runtime" section of the Dockerfile, the text says to add "libxext6" to the list, but then the example text seems to have removed the libraries which are already defined in this section: "telnet, netcat, psmisc". I assume it should be appended to this list, not replace it.

I see the next paragraph talks about removing the RTEMS-specific packages, but it isn't clear what these packages are.
Not really related to this page, but I just noticed: ioc-adurl/.github/workflows/buiild.yml - the "buiild" looks like a typo
The CI for "build-push-images(linux)" also fails with the Uppercase username issue. I'm assuming this is because you haven't pushed the new version yet.

- [ ] "test_generic_ioc":

Add a newline to the end of the st.cmd example as it's required by the startup script
To make the tests work, we had to do:
epicsEnvSet("EPICS_CA_REPEATER_PORT","7065")
epicsEnvSet("EPICS_CA_SERVER_PORT","7064")
-v /tmp:/tmp
Under "Try out some GUI":
Typo: "ADUrl dies not"
We had a discussion about inside vs outside the container, regarding what files are mounted and what would be lost when the container restarts
The simple fix for the tutorial is to check out your version of ioc-adurl into a specific folder inside the existing workspace

- [ ] "reference/cli"

As discussed, the output here is out of date as there's no --image-registry anymore
Can you make Sphinx execute ec --help​ and dump the text output into this document, instead of hard-coding it?

Thanks,
Alex Wells

**Comment by gilesknap** [comment]
> "Setup a Devcontainer":
> 
> The note to ensure you have installed the DevContainer extension is a little confusing. It was not obvious to me that I had just installed it as part of the RemoteDevelopment "extension", which is really a collection of 4 extensions in one. Perhaps either call out the 4 extensions that the pack will install, or tell users to ensure they have all extensions from the previous page?

This is an artifact of Callum inserting this page as a standalone reference for using devcontainers.

Tidied up the instructions on this in 690a7283536c352baf8545327fba187f9915ea43

**Comment by gilesknap** [comment]
> "epics_devcontainer":
> 
> The "REPLACE all environment below with your details " section is a bit odd - the default checkout of the repo provided 
earlier in the tutorials already has good values written in it, including KUBECONFIG pointing to config_pollux and the Helm Registry pointing to helm-test.diamond.ac.uk/iocs. As discussed, it really wasn't clear to me that I had to change the K8S_HELM_REGISTRY variable, especially as the other two variables appear to be correct

Reworded to clarify that it is K8S_HELM_REGISTRY that needs changing.
73bd0de

**Comment by gilesknap** [comment]
> "create_beamline":
> 
> Minor typo: "To do this got to..." should be "To do this go to..." When doing 'git commit -m "rename blxxi to bl01t"' from inside the dev container, git automatically set the author to "root" with an email of "[root@pc0103.cs.diamond.ac.uk](mailto:root@pc0103.cs.diamond.ac.uk)". This doesn't feel correct, and the docs should at least provide some sort of warning or guidance. When I pushed the newly created tag, I used "git push --tags". This had the inadvertant effect of pushing your tags "23.4.1" and "23.3.1" as well. Any way to avoid this?

@AlexanderWells-diamond to avoid the pushing of tags use `git push origin 23.4.2` (the docs already said this) I have also removed as many tags as I can from the template project but need to keep the release tags.

9d7980c adds a note about setting git user.

**Comment by gilesknap** [comment]
> * [ ]  "deploy_example":
> 
> Probably worth putting a note somewhere to change the IOC name to the custom one, if the user in previous sections had used a custom name.

62ebc65ca15836cae5b12b294534521543898aa8 adds a comment to this effect.


> When examining the logs of the IOC I saw this error: "recGblRecordError: devStringinEnvVar (init_record) Illegal INP parm field Illegal field value PV: BL01T-EA-IOC-01:TIMEZONE"
> I'm not sure if its important, but somehow two different pods had the same IP address:
> [E7](main)[bl01t]$ ec ps -w
> POD                                VERSION            STATE     RESTARTS   STARTED                IP              GENERIC_IOC_IMAGE
> bl01t-ea-ioc-02-6b7bcfdc78-g5bfj   2023.4.20-b12.40   Running   0          2023-04-20T12:43:50Z   172.23.168.23   ghcr.io/epics-containers/ioc-template-rtems-runtime:23.4.2
> blxxi-ea-ioc-01-cf5f6d94b-sqs4c    23.3.3             Running   1          2023-04-13T10:41:36Z   172.23.168.24   ghcr.io/epics-containers/ioc-adsimdetector-linux-runtime:23.3.4
> eyh46967-ioc-01-5b9944dc49-fr86k   23.4.21            Running   0          2023-04-21T09:08:12Z   172.23.168.23   ghcr.io/epics-containers/ioc-adsimdetector-linux-runtime:23.3.4

The ip address is the host address of the node on which the IOC pod was scheduled. These could easily be the same and yes then there would be PV name clashes. The error message is benign and I'll add a comment to that effect.

62ebc65ca15836cae5b12b294534521543898aa8 adds your user ID to the start of all PVS in this tutorial. (will need to do this for later tutorials too I think)



> I cannot run the EDM GUI from within the devcontainer, using either podman or docker. 
> If I try and run the EDM GUI outside of the container, by either "./blxxi-ea-ioc-01-gui.sh" or "opi/./blxxi-ea-ioc-01-gui.sh" (from the relevant paths) I see an error:
> [eyh46967@pc0103 opi]$ ./blxxi-ea-ioc-01-gui.sh
> ./launcher.sh: line 12: --privilege : command not found

@AlexanderWells-diamond I think we fixed this didn't we?? It runs for me.

**Comment by gilesknap** [comment]
> > @AlexanderWells-diamond I think we fixed this didn't we?? It runs for me.
> 
> I think we had to add a "--privilege" flag to a call somewhere to make it run?

I added that into the blxxi-template code - I just checked and I can see why you got the error above. I believe it is now fixed
https://github.com/epics-containers/blxxi-template/commit/cf84b80d89e99f4aac2a2469caa7270f745ebb2c

**Comment by gilesknap** [comment]
> * [ ]  "ioc_changes":
> 
> Trying to run this command: "ec dev ioc-launch iocs/bl01t-ea-ioc-01 --tag 23.3.4" gives this error: RuntimeError: Missing file /home/eyh46967/.bashrc_dev, please copy from .devcontainer or create your own After our discussion we agreed this was a bug and shoul not be required
> 
> The tag number in the above command should probably be made more clear that it is NOT the same as the tag number we created in a previous step In "Deploying a Beta IOC Instance to The Cluster" section there appears to be a malformed link to "05_deploy_example"

I've changed the behaviour of `ec` to fix the issue and not require a --tag for this invocation.
https://github.com/epics-containers/epics-containers-cli/commit/ce60e5d00582a9c6d2c9e1f2b4d69458ca54f6b2

a133776 updated the docs accordingly

**Comment by gilesknap** [comment]
these reviews are no longer relevant as the framework has changed significantly.
